name: CI - PDFLatex build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: LaTeX compilation
      uses: dante-ev/latex-action@master
      with:
        root_file: notes/main.tex
        compiler: latexmk # optional, default is latexmk

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: pdf
        path: notes/main.pdf
        retention-days: 30
        if-no-files-found: error

    - name: Move file to a branch
      if: success() && github.ref == 'refs/heads/master'
      run: |
        git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git config --global user.name "$GITHUB_ACTOR"
        git fetch --all
        git checkout pdf
        mv notes/main.pdf Quasar-case_studies.pdf
        git add Quasar-case_studies.pdf
        git commit -m "pdf compile"
        git push origin pdf
